root = "."
tmp_dir = "build"

[build]
  bin = "./build/pocket-id"
  cmd = "CGO_ENABLED=0 go build -o ./build/pocket-id ./cmd"
  exclude_dir = ["resources", "build", "data"]
  exclude_regex = [".*_test\\.go"]
  stop_on_error = true

[misc]
  clean_on_exit = true
